/*
 * This file is generated by jOOQ.
*/
package com.zxy.product.test.jooq;


import com.zxy.product.test.jooq.tables.Test;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MyTest2 extends SchemaImpl {

    private static final long serialVersionUID = 813424521;

    /**
     * The reference instance of <code>my_test2</code>
     */
    public static final MyTest2 MY_TEST2_SCHEMA = new MyTest2();

    /**
     * The table <code>my_test2.test</code>.
     */
    public final Test TEST = com.zxy.product.test.jooq.tables.Test.TEST;

    /**
     * No further instances allowed
     */
    private MyTest2() {
        super("my_test2", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Test.TEST);
    }
}
