/*
 * This file is generated by jOOQ.
*/
package com.zxy.product.test.jooq;


import com.zxy.product.test.jooq.tables.Test;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in my_test2
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>my_test2.test</code>.
     */
    public static final Test TEST = com.zxy.product.test.jooq.tables.Test.TEST;
}
