/*
 * This file is generated by jOOQ.
*/
package com.zxy.product.test.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITest extends Serializable {

    /**
     * Setter for <code>my_test2.test.id</code>.
     */
    public void setId(String value);

    /**
     * Getter for <code>my_test2.test.id</code>.
     */
    public String getId();

    /**
     * Setter for <code>my_test2.test.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>my_test2.test.name</code>.
     */
    public String getName();

    /**
     * Setter for <code>my_test2.test.age</code>.
     */
    public void setAge(Integer value);

    /**
     * Getter for <code>my_test2.test.age</code>.
     */
    public Integer getAge();

    /**
     * Setter for <code>my_test2.test.sex</code>.
     */
    public void setSex(Integer value);

    /**
     * Getter for <code>my_test2.test.sex</code>.
     */
    public Integer getSex();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ITest
     */
    public void from(com.zxy.product.test.jooq.tables.interfaces.ITest from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ITest
     */
    public <E extends com.zxy.product.test.jooq.tables.interfaces.ITest> E into(E into);
}
