/*
 * This file is generated by jOOQ.
*/
package com.zxy.product.test.jooq.tables;


import com.zxy.product.test.jooq.Keys;
import com.zxy.product.test.jooq.MyTest2;
import com.zxy.product.test.jooq.tables.records.TestRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Test extends TableImpl<TestRecord> {

    private static final long serialVersionUID = 417014987;

    /**
     * The reference instance of <code>my_test2.test</code>
     */
    public static final Test TEST = new Test();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TestRecord> getRecordType() {
        return TestRecord.class;
    }

    /**
     * The column <code>my_test2.test.id</code>.
     */
    public final TableField<TestRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(11).nullable(false), this, "");

    /**
     * The column <code>my_test2.test.name</code>.
     */
    public final TableField<TestRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

    /**
     * The column <code>my_test2.test.age</code>.
     */
    public final TableField<TestRecord, Integer> AGE = createField("age", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>my_test2.test.sex</code>.
     */
    public final TableField<TestRecord, Integer> SEX = createField("sex", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>my_test2.test</code> table reference
     */
    public Test() {
        this("test", null);
    }

    /**
     * Create an aliased <code>my_test2.test</code> table reference
     */
    public Test(String alias) {
        this(alias, TEST);
    }

    private Test(String alias, Table<TestRecord> aliased) {
        this(alias, aliased, null);
    }

    private Test(String alias, Table<TestRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return MyTest2.MY_TEST2_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TestRecord> getPrimaryKey() {
        return Keys.KEY_TEST_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TestRecord>> getKeys() {
        return Arrays.<UniqueKey<TestRecord>>asList(Keys.KEY_TEST_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Test as(String alias) {
        return new Test(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Test rename(String name) {
        return new Test(name, null);
    }
}
